version: '3'
services:
    test-nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./project:/app
        depends_on:
            - test-php-fpm
        ports:
            - "8080:80"
    test-php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./project:/app
        depends_on:
            - test-mysql
    test-php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./project:/app
            - composer:/root/.composer/cache
        depends_on:
            - test-mysql
    test-mysql:
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: test-mysql

volumes:
    test-mysql:
    composer: